server:
  port: 9191
spring:
  application:
    name: logistics-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///logistics?serverTimezone=UTC
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/
mybatis:
  type-aliases-package: com.cssl.entity
  mapper-locations: classpath:com/cssl/mailing/mapper/*.xml

mybatis-plus:
  type-aliases-package: com\cssl\entity
  configuration:
    map-underscore-to-camel-case: true
